#! /bin/bash

sed -i '/^output e\?DP-[0-9]/d' $HOME/.config/sway/config

if [[ $2 == 'external' ]]
 then
  echo 'output eDP-1 disable' >> $HOME/.config/sway/config
fi

if [[ $3 == 'hi' ]]
 then
  echo "output DP-1 scale ${4:1.5}" >> $HOME/.config/sway/config
  echo "output DP-2 scale ${4:1.5}" >> $HOME/.config/sway/config
fi

export PATH=$PATH:$HOME/bin/:$HOME/bin/$(hostname)/:$HOME/scripts/
export TERM=konsole
export BROWSER=chromium

if [[ "$XDG_RUNTIME_DIR" == "" ]]
then
  export XDG_RUNTIME_DIR=/tmp
fi

export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pictures"
export XDG_VIDEOS_DIR="$HOME/videos"
export XDG_SESSION_TYPE=wayland-egl

sway 2> ~/sway.log
